name: Auto Commit Scheduler

on:
  workflow_dispatch:  
  schedule:
    - cron: '40 10 * * *' 
jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Random Commits
        run: |
          RANDOM_COMMITS=$((RANDOM % 5 + 1))  # Jumlah commit acak (1-5)
          echo "Creating $RANDOM_COMMITS commits"

          for i in $(seq 1 $RANDOM_COMMITS); do
            echo "Commit #$i at $(date)" >> random_file.txt
            git add random_file.txt
            git commit -m "Random commit #$i at $(date)"
          done

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://ABCDullahh:${GH_TOKEN}@github.com/ABCDullahh/Dawet-IJO.git
          git pull origin main  # Pastikan sinkronisasi dengan branch utama
          git push origin main
